[cam_0]
name = "rightCamera"
size = [ 320, 256,]
matrix = [ [ 403.15, 0.0, 320.0,], [ 0.0, 403.15, 256.0,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.0, 0.0, 0.0, 0.0, 0.0,]
rotation = [ 0.09560452004827606, 0.20101721238189774, -0.18790278840758118,]
translation = [ -0.3059347509107901, 0.2106173426943166, 0.30946055446265613,]

[cam_1]
name = "leftCamera"
size = [ 320, 256,]
matrix = [ [ 403.15, 0.0, 320.0,], [ 0.0, 403.15, 256.0,], [ 0.0, 0.0, 1.0,],]
distortions = [ 0.0, 0.0, 0.0, 0.0, 0.0,]
rotation = [ -0.20909482988466396, 1.646588826580563, 0.7078329998406844,]
translation = [ -1.6371034033730263, -0.4964763690940176, 1.2902212413175833,]

[metadata]
